apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: med-record-hpa
  namespace: med-record-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: med-record
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
