apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: med-record
  newName: vgmarques/med-record
  newTag: newversion
- name: vgmarques/gitopsfc
  newName: vgmarques/gitopsfc
  newTag: 9c60e76528c31ec4f71b2de205d899c70ffc0f12
