apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
# - name: med-record
#   newName: vgmarques/med-record
#   newTag: newversion
- name: goserver
  newName: vgmarques/gitopsfc
  newTag: 34ef0f0e187c641d05a59c0c3e2407a8f76a6abb
