apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
# - name: med-record
#   newName: vgmarques/med-record
#   newTag: newversion
images:
- name: goserver
  newName: vgmarques/hello-go-k8s
  newTag: 34ef0f0e187c641d05a59c0c3e2407a8f76a6abb
- name: vgmarques/gitopsfc
  newName: vgmarques/gitopsfc
  newTag: dd81faaf9fd84f9da7dd6ef4b6106802e1a8e418
