apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: vgmarques/gitopsfc
  newTag: dd81faaf9fd84f9da7dd6ef4b6106802e1a8e418
